name: "Meticulous Test"

on:
  issue_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write
  actions: write
  issues: write
  statuses: write

jobs:
  run-meticulous:
    name: Run Meticulous Test
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/meticulous')
    runs-on: ubuntu-latest
    steps:
      - name: Add rocket reaction to comment
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            
            await github.rest.reactions.createForIssueComment({
              owner,
              repo,
              comment_id: context.payload.comment.id,
              content: 'rocket'
            });

      - name: Get PR branch
        uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch

      - name: Set latest commit status as pending
        uses: myrotvorets/set-commit-status-action@master
        with:
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          context: "Meticulous Tests"
          status: pending
          description: "Запуск Meticulous тестов..."

      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}

      - name: Setup Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-modules-${{ runner.os }}

      - name: Install dependencies
        run: |
          npm ci

      - name: Install Angular CLI
        run: |
          npm install -g @angular/cli

      - name: Build project
        run: |
          ng build

      - name: Start project
        run: |
          ng serve --port 4200 &
          sleep 5

      - name: Run Meticulous tests
        id: meticulous
        uses: alwaysmeticulous/report-diffs-action/cloud-compute@v1
        with:
          api-token: ${{ secrets.METICULOUS_API_TOKEN }}
          app-url: "http://localhost:4200/"

      - name: Set latest commit status as ${{ job.status }}
        uses: myrotvorets/set-commit-status-action@master
        if: always()
        with:
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          context: "Meticulous Tests"
          status: ${{ job.status }}
          description: "Проверка ${{ job.status == 'success' && 'успешно завершена' || 'завершилась с ошибкой' }}"

      - name: Add result comment to PR
        uses: actions/github-script@v6
        if: always()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const success = '${{ job.status }}' === 'success';
            const reportUrl = '${{ steps.meticulous.outputs.report-url }}' || '';
            const issue_number = context.issue.number;
            
            // Create URL that will pre-fill comment with /meticulous command for rerun
            const rerunUrl = `https://github.com/${owner}/${repo}/pull/${issue_number}?comment=%2Fmeticulous`;
            
            let body = `## Результат проверки Meticulous\n\n`;
            body += success ? '✅ Проверка успешно завершена!' : '❌ Проверка завершилась с ошибкой';
            
            if (reportUrl) {
              body += `\n\n[Посмотреть полный отчет](${reportUrl})`;
            }
            
            body += `\n\n[Подробности запуска](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})`;
            
            // Add rerun button
            body += `\n\n<p align="center">
              <a href="${rerunUrl}">
                <img src="https://img.shields.io/badge/ЗАПУСТИТЬ-ЗАНОВО-FF5733?style=for-the-badge" alt="Запустить заново" width="300" />
              </a>
            </p>`;
            
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner,
              repo,
              body
            });

  add-help-comment:
    name: Add Help Comment
    if: github.event.issue.pull_request && (contains(github.event.comment.body, '/help') || contains(github.event.comment.body, '/помощь'))
    runs-on: ubuntu-latest
    steps:
      - name: Add help comment
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const issue_number = context.issue.number;
            
            // Create URL that will pre-fill comment with /meticulous command
            const runUrl = `https://github.com/${owner}/${repo}/pull/${issue_number}?comment=%2Fmeticulous`;
            
            const body = `## Команды Meticulous
            
            Доступные команды для этого PR:
            
            - \`/meticulous\` - Запустить проверку Meticulous
            - \`/help\` или \`/помощь\` - Показать эту справку
            
            <p align="center">
              <a href="${runUrl}">
                <img src="https://img.shields.io/badge/ЗАПУСТИТЬ-ТЕСТЫ-44CC11?style=for-the-badge" alt="Запустить тесты" width="300" />
              </a>
            </p>
            `;
            
            await github.rest.issues.createComment({
              issue_number,
              owner,
              repo,
              body
            });
            
            await github.rest.reactions.createForIssueComment({
              owner,
              repo,
              comment_id: context.payload.comment.id,
              content: 'eyes'
            }); 