name: "Add PR Comment"

on:
  pull_request_target:
    types: [opened, reopened]

permissions:
  pull-requests: write

jobs:
  add-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Add information comment
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const issue_number = context.issue.number;
            
            // Create URL that will pre-fill comment with /meticulous command
            const commentUrl = `https://github.com/${owner}/${repo}/pull/${issue_number}?comment=%2Fmeticulous`;
            
            const body = `## Meticulous тесты
            
            <p align="center">
              <a href="${commentUrl}">
                <img src="https://img.shields.io/badge/ЗАПУСТИТЬ-ТЕСТЫ-44CC11?style=for-the-badge" alt="Запустить тесты" width="300" />
              </a>
            </p>
            
            > При нажатии на кнопку, в поле комментария будет автоматически добавлена команда \`/meticulous\`. Нажмите Enter для запуска тестов.
            
            Другие доступные команды:
            \`/help\` или \`/помощь\` - показать справку
            `;
            
            await github.rest.issues.createComment({
              issue_number,
              owner,
              repo,
              body
            }); 