name: Block Merge
on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]
jobs:
  block:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const labels = context.payload.pull_request.labels.map(l => l.name);
            if (labels.includes('blocked')) {
              core.setFailed('Merge blocked by label');
            } 