name: Block PR
on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]
permissions:
  issues: write
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            if (!pr) return;
            
            // Если это событие изменения лейбла - проверяем только лейблы
            if (context.eventName === 'pull_request' && (context.payload.action === 'labeled' || context.payload.action === 'unlabeled')) {
              const labels = (pr.labels || []).map(l => l.name);
              if (labels.includes('blocked')) {
                core.setFailed('PR blocked by label');
              }
              return;
            }
            
            // Для других событий проверяем коммиты
            const count = pr.commits || 0;
            if (count > 10) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                labels: ['blocked']
              });
              core.setFailed('Too many commits');
            }
