name: Block PR
on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/github-script@v7
        with:
          script: |
            const count = await exec.exec('git', ['rev-list', '--count', `origin/${{ github.base_ref }}..${{ github.head_ref }}`], {silent: true});
            if (count > 10) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: ['blocked']
              });
            }
            const labels = context.payload.pull_request.labels.map(l => l.name);
            if (labels.includes('blocked')) {
              core.setFailed('Merge blocked by label');
            }
