name: "Meticulous Test Runner"

on:
  workflow_dispatch:
    inputs:
      head_ref:
        description: 'Ветка PR (head)'
        required: true
      head_sha:
        description: 'SHA коммита PR'
        required: true
      base_ref:
        description: 'Целевая ветка (base)'
        required: true
      base_sha:
        description: 'SHA целевой ветки'
        required: true
      pr_number:
        description: 'Номер PR'
        required: true

permissions:
  contents: read
  pull-requests: write
  actions: write
  issues: write
  statuses: write

jobs:
  run-meticulous:
    name: Run Meticulous Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.head_ref }}
          fetch-depth: 0

      - name: Setup Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-modules-${{ runner.os }}

      - name: Install dependencies
        run: |
          npm ci

      - name: Install Angular CLI
        run: |
          npm install -g @angular/cli

      - name: Build project
        run: |
          ng build

      - name: Start project
        run: |
          ng serve --port 4200 &
          sleep 5

      - name: Run Meticulous tests
        id: meticulous
        uses: alwaysmeticulous/report-diffs-action/cloud-compute@v1
        with:
          api-token: ${{ secrets.METICULOUS_API_TOKEN }}
          app-url: "http://localhost:4200/"
          base-commit: ${{ github.event.inputs.base_sha }}
          head-commit: ${{ github.event.inputs.head_sha }}

      - name: Set latest commit status as ${{ job.status }}
        uses: myrotvorets/set-commit-status-action@master
        if: always()
        with:
          sha: ${{ github.event.inputs.head_sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          context: "Meticulous Tests"
          status: ${{ job.status }}
          description: "Проверка ${{ job.status == 'success' && 'успешно завершена' || 'завершилась с ошибкой' }}"

      - name: Add result comment to PR
        uses: actions/github-script@v6
        if: always()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const issue_number = ${{ github.event.inputs.pr_number }};
            const success = '${{ job.status }}' === 'success';
            const reportUrl = '${{ steps.meticulous.outputs.report-url }}' || '';
            
            let body = `## Результат проверки Meticulous\n\n`;
            body += success ? '✅ Проверка успешно завершена!' : '❌ Проверка завершилась с ошибкой';
            
            if (reportUrl) {
              body += `\n\n[Посмотреть полный отчет](${reportUrl})`;
            }
            
            body += `\n\n[Подробности запуска](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})`;
            
            body += `\n\nДля повторного запуска тестов используйте команду \`/meticulous\``;
            
            body += `\n\n---\n\nСравнение: ветка PR (\`${{ github.event.inputs.head_ref }}\`) с целевой веткой (\`${{ github.event.inputs.base_ref }}\`)`;
            
            await github.rest.issues.createComment({
              issue_number,
              owner,
              repo,
              body
            }); 